### ISSUE TITLE
Listening only in IPV6 but not in IPV4

### ISSUE THREAD

**Issue by profjefferson** [bitnami/bitnami-docker-dreamfactory#12]
Running the composer like doc show, the container only listen on IPV6 protocol, what could be?

**Comment by andresbono** [comment]
Hi @profjefferson,

How did you check that it is not listening IPv4? Can't you access the application with an IPv4 ip address? You can try  the local address`127.0.0.1`. 

Let us know if it works for you or not. If not, we will continue digging into the issue.

-Andrés B.
