### ISSUE TITLE
Unable to connect with postgres container

### ISSUE THREAD

**Issue by streetcoder** [bitnami/bitnami-docker-dreamfactory#14]
Hello,

I have installed postgres in a container under the network 'bridge'. When I try to connect, it returns error after a while that is "SQLSTATE[08006] [7] timeout expired".  But I can connect to postgres which is not dockerized. Could you tell me how can I fix it?

**Comment by streetcoder** [comment]
Please close this issue. I have fixed it. Just updated the postgres's network to dreamfactory. anyway thanks.

**Comment by navidman** [comment]
can you please share your docker-compose.yml file? Im trying to connect postgres to dreamfactory but I couldnt do that so far!
