### ISSUE TITLE
Setup Admin And Import Package

### ISSUE THREAD

**Issue by kachatzis** [bitnami/bitnami-docker-dreamfactory#16]
Is there a way to setup admin and import packages automatically?
I tried changing the starting-point.sh but this happens:

```
# php /opt/bitnami/dreamfactory/artisan df:import-pkg $PACKAGE_URI --password=$PACKAGE_SECRET

REST Exception #403 > POST access to component 'role' of service 'system' is not allowed by this user's role.
REST Exception #403 > Failed to insert roles. POST access to component 'role' of service 'system' is not allowed by this user's role.
```
As for adding the admin, i guess the only way is using df:setup and passing the values with a separate script.

**Comment by javsalgar** [comment]
Hi,

Could you detail a bit more what the necessary commands are? Could you try doing the same in the `run.sh` script?

**Comment by kachatzis** [comment]
Hello,
I can't find the run.sh script but i am attaching the container directly, so i have access after the installation is complete. Maybe I will modify the scripts to run my own, with a delay after the installation.

I am creating the admin user manually right now, but it shouldn't be too hard to automate by using something like this:
`printf 'admin\nemail@example.com\n...' | php /opt/bitnami/dreamfactory/artisan df:setup`

The error  `POST access to component 'role' of service 'system' is not allowed by this user's role` is what I can't work out.

**Comment by javsalgar** [comment]
Ok, I saw that this container does not include the run.sh script.

Let's do the following:

- Launch the container by executing `docker-compose run dreamfactory bash`

- Once you are inside execute these commands

```
. /opt/bitnami/base/functions
. /opt/bitnami/base/helpers
nami_initialize apache php libphp dreamfactory
```

- After this, dreamfactory is initialized, then you can execute your commands

**Comment by kachatzis** [comment]
I ran the commands (both before & after creating the admin) but it has the same result.

![Screenshot from 2019-04-23 22-04-54](https://user-images.githubusercontent.com/20270035/56610342-daa46a80-6617-11e9-84a2-fdf0555dff68.png)

Also i tried importing the same package using the admin panel and:

`Failed to import package from http://s3.eu-central-1.amazonaws.com/X.zip. fopen(/opt/bitnami/php/tmp/X.zip): failed to open stream: Permission denied`

Then i imported the package by downloading first and then uploading the package, and it worked.
Doing the same directly via console still gives me the same error.

**Comment by javsalgar** [comment]
Hi,

I'm concerned about not being able to import a plugin using the admin panel. Could you detail the steps and a example plugin that does not work?
