### ISSUE TITLE
Use PostgreSQL for config database

### ISSUE THREAD

**Issue by mludvig** [bitnami/bitnami-docker-dreamfactory#18]
**Description**

Now that DreamFactory requires a **Silver license** to use *MySQL / MariaDB* but doesn't require a license to use *PostgreSQL* it would be very convenient if this Bitnami container supported PostgreSQL as a configuration backend as well.

DreamFactory already supports it so it's just a matter of adding support to the Bitnami infrastructure. 

**Example**

FYI a working `/bitnami/dreamfactory/.env` with PostgreSQL support may look like this:

```
DB_CONNECTION=pgsql
DB_HOST=postgresql
DB_PORT=5432
DB_DATABASE=dreamfactory
DB_USERNAME=dreamfactory
DB_PASSWORD=Passw0rd
```

At the moment we need MySQL for the config database and PostgreSQL for the app database, that's quite inconvenient.

**Comment by dgomezleon** [comment]
Hello @mludvig ,

> Now that DreamFactory requires a Silver license to use MySQL / MariaDB but doesn't require a license to use PostgreSQL it would be very convenient if this Bitnami container supported PostgreSQL as a configuration backend as well.

We use MariaDB in all our DF solutions (Stack, containers...). This is the default database that they use, as you can see [here](https://wiki.dreamfactory.com/DreamFactory/Installation/Databases/MySQL)

```
MySQL and its clones make great system databases for DreamFactory. We frequently use MariaDB, as it is open source. For help installing MariaDB, see the | MariaDB Download System.
```

Could you please let me know if you have found any issue with MariaDB or is there something that I'm missing?

**Comment by mludvig** [comment]
DreamFactory can use either MySQL/MariaDB or PostgreSQL as its *config database*, so far so good that you support MariaDB for that.

However using MySQL/MariaDB for the *DF api service datastore* requires a paid *Silver license*. On the other hand using PostgreSQL for *api service datastore* doesn't require a license. Hence most users who need a SQL backend will opt for PostgreSQL.

These users in turn need to **run two databases** - MySQL/MariaDB for the config database and PostgreSQL for the api database. That's an unnecessary overhead since DF can happily store its config in PostgreSQL. All we need is a PgSQL support in the Bitnami scripts.

If you want to test it bring up a fresh new DreamFactory installation with your provided `docker-compose.yml`, create admin user and go to *Create Service*. Then for *Service Type* select *Database -> MySQL* and you will get a message *" This feature requires a DreamFactory SILVER product subscription."*

![Screenshot_133_Selection](https://user-images.githubusercontent.com/745857/74682121-0a1d0700-522a-11ea-83f1-4c6eb123c157.png)

Therefore I suggest you switch or add PostgreSQL support for the config backend as well to remove the need for running two database engines. 

Hope that makes sense now :)

**Comment by miracle2come** [comment]
Hi there,

I have the same issue.... it was very frustrating when DF just moved MySQL support out of free license. I didn't believe they will do that, but it is what it is. After we have to migrate our databases to Postgres. At the same time, there is no Postgres client in container so you have to customize it. Not sure if adding couple of packages to container is that difficult but will be very handy for us.

Thank you
Kosta

**Comment by dgomezleon** [comment]
Thank @mludvig ,

That makes perfect sense. Thanks for clarifying it.

We are going to check this with the DreamFactory team. We will keep you in the loop.

Regards

**Comment by mludvig** [comment]
@dgomezleon any update? We'd like to deploy DreamFactory without MySQL. Happy to do be a tester if you want :)
Thanks!

**Comment by marcosbc** [comment]
Hi @mludvig, it seems like the DreamFactory team agrees that it would make sense to add PostgreSQL support, and we're currently evaluating the technical details with them. Unfortunately there's no ETA, but we'll keep you in the loop.

**Comment by mludvig** [comment]
Not stale. Still waiting for a resolution. Thanks.

**Comment by marcosbc** [comment]
Hi @mludvig, sorry for the delay. It seems like we can proceed with adding support for PostgreSQL services without need to wait for DreamFactory's response, and it seems like a simple change.

We have already started looking into this, but unfortunately cannot give an ETA for when it will be implemented. In any case we will keep you in the loop.

**Comment by marcosbc** [comment]
Hi @mludvig, we have implemented support for PostgreSQL as config databases. Check the release notes for [`4.0.1-debian-10-r19`](https://github.com/bitnami/bitnami-docker-dreamfactory/#401-debian-10-r19) to read more on this change.

To enable it, you just need to enable the environment variable `DREAMFACTORY_DATABASE_TYPE=postgresql` for the DreamFactory container, and add a PostgreSQL container to your `docker-compose.yml` file (it should be named "postgresql" if you want to avoid having to specify the hostname).

**Comment by mludvig** [comment]
Brilliant, thanks a lot! I will give it a try in the next couple of days.
