### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by blondie63** [bitnami/bitnami-docker-dreamfactory#21]
Hi all, i need to understand the use of Environment variables, for example MARIADB_HOST is used to set host name of internal MariaDB or generic host name so i can set my external Host ?
Same thing for Mongo and others

For example i'd like to test dreamfactory connected to my host with MariaDB
Thanks

**Comment by dani8art** [comment]
Hi @blondie63, sure you can use them to point to your own hosts, for more info you can go to https://github.com/bitnami/bitnami-docker-dreamfactory#configuration

Thanks!

**Comment by blondie63** [comment]
ok done, thanks
