### ISSUE TITLE
DF version 4.9 missing

### ISSUE THREAD

**Issue by tvarsis** [bitnami/bitnami-docker-dreamfactory#25]
Was released one month ago, but these images still runs 4.8.

**Comment by carrodher** [comment]
Thanks for letting us know, this new version requires some manual changes on our side, we are currently working on them.

We will update this issue once the new version is ready. I will add the on-hold label to prevent the stale bot from closing the ticket while we work on the associated tasks.

**Comment by tvarsis** [comment]
4.9 have been released.
