### ISSUE TITLE
Version 4.8 issues with entry scripts for existing installations

### ISSUE THREAD

**Issue by tvarsis** [bitnami/bitnami-docker-dreamfactory#26]
I already have an existing DF instance running with everything setup, and in version 4.6 I can run:

`docker-compose down && docker-compose up -d`

And everything will work fine.

In version 4.8 when I run the same thing, DF gets into a broken state and it looks like it tries to run full setup always instead of using existing installation. When trying to login to the Admin console, you will get this error: 

![image](https://user-images.githubusercontent.com/10090010/138604776-16a1a88a-fc5c-4f5c-ade3-d72fb7deb2ed.png)

And logs will show:
`Invalid token: Token Signature could not be verified.`

From this point, the instance is broken and restarting the server or docker containers won't work. The only thing that fixes is is to run this:

`sudo docker exec dreamfactory_dreamfactory_1 bash -c "cd /opt/bitnami/dreamfactory && php artisan config:clear"`

So it looks like there is an issue with how the configs are applied/cleared when an existing installation already exists. Adding the above config:clear command as part of the steps before clearing cache in the init scripts, might be enough to fix it, but have not verified if it is a full solution.

**Comment by tvarsis** [comment]
@alemorcuq I would if I could. But this repo seems very complex to me with so many different scripts and files that are being run all over the place, compared to the https://github.com/dreamfactorysoftware/df-docker repo which seems much more straight forward. Can't even find where the APP_KEY var is handled in this repo (if it even is handled), which is easy to find in in the original DF one.

**Comment by alemorcuq** [comment]
Could you try something to check if it fixes your issue?

In the `/opt/bitnami/scripts/libdreamfactory.sh` file there's these lines:

```
    info "Clearing cache"
    dreamfactory_execute "config:cache"
    dreamfactory_execute "cache:clear"
```

Can you change that `config:cache` command to `config:clear` and check if you are able to bring the container down and up without issues?

**Comment by tvarsis** [comment]
@alemorcuq I can confirm that that change fixes the issue and the restarts works fine again. Thanks!

**Comment by alemorcuq** [comment]
Thanks for the PR! The next tag released should have this change implemented.
