### ISSUE TITLE
Warning on startup that Cassandra lib is missing

### ISSUE THREAD

**Issue by tvarsis** [bitnami/bitnami-docker-dreamfactory#28]
When you start up the 4.9.0 container, it gives this warning which indicates that the correct Cassandra libs are missing:

`PHP Warning:  PHP Startup: Unable to load dynamic library 'cassandra' (tried: /opt/bitnami/php/lib/php/extensions/cassandra (/opt/bitnami/php/lib/php/extensions/cassandra: cannot open shared object file: No such file or directory), /opt/bitnami/php/lib/php/extensions/cassandra.so (/opt/bitnami/php/lib/php/extensions/cassandra.so: cannot open shared object file: No such file or directory)) in Unknown on line 0`

I don't use Cassandra myself, so not sure what the exact impact for this is, but I would guess Cassandra does not work unless the lib is installed correctly. I guess it is related to this line in postunpack.sh:

`php_conf_set extension "cassandra"`

Which I think tries to load an extension that is not yet installed.

**Comment by yilmi** [comment]
Hi @tvarsis, just wanted to let you know that I'm looking into this issue 👍

**Comment by yilmi** [comment]
Hi @tvarsis,

Got an explanation on this, we had to remove the pecl cassandra library as it became unsupported after updating from PHP 7.3 to 7.4. Plus, this pecl package, is currently under maintenance so there's no visibility regarding PHP 7.4 support.

We've updated the readme, and removed the cassandra library loading step. Once released you should be able to consume the tag [4.9.0-debian-10-r8](https://github.com/bitnami/bitnami-docker-dreamfactory/releases/tag/4.9.0-debian-10-r8).

Thanks for reporting this!

**Comment by tvarsis** [comment]
@yilmi Great,and thanks for the explanation and for fixing it!

**Comment by yilmi** [comment]
No worries, thanks for letting us know! I just checked if it was released yesterday, but it seems that my changes got in lagte. I expect them to be released today, most likely by the EOD. 👍

**Comment by yilmi** [comment]
The tag is available, if you don't mind verifying and closing this issue. Thanks!

**Comment by tvarsis** [comment]
@yilmi I tested the latest build and can confirm that the warning for Cassandra is not gone. Thanks!
