### ISSUE TITLE
Running as user docker -u

### ISSUE THREAD

**Issue by zorel** [bitnami/bitnami-docker-dreamfactory#5]
When trying to run the container with docker -u (as it's forced on with openshift for example), it fails with:

```
docker run -u 1001 bitnami/dreamfactory

Welcome to the Bitnami dreamfactory container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-dreamfactory
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-dreamfactory/issues
Send us your feedback at containers@bitnami.com

INFO  ==> Starting dreamfactory...
nami    ERROR Cannot find any module matching the provided specification 'apache'
```

Is there a way to build the image to support running as user?

**Comment by andresbono** [comment]
Hi @zorel, this feature for our containers was already requested here: [bitnami-docker-mongodb #75](https://github.com/bitnami/bitnami-docker-mongodb/issues/75) and we are currently working on it. As you point, once this is supported, you will be able to use the `--user` option and to run your containers on OpenShift.

Your interest is really appreciated!
