### ISSUE TITLE
`DREAMFACTORY_PASSWORD` does not work

### ISSUE THREAD

**Issue by chipironcin** [bitnami/bitnami-docker-dreamfactory#8]
**Description**
Setting `DREAMFACTORY_PASSWORD` does not have any impact on the deployment.

**Steps to reproduce the issue:**

1. Add `DREAMFACTORY_PASSWORD` as env variable to docker compose
2. Bring up docker compose
3. Password is not set to the one I wrote

**Describe the results you received:**

Application password is not set to the one I wrote

**Describe the results you expected:**

Password set to the one I specified using `DREAMFACTORY_PASSWORD`

**Version**

- Output of `docker version`:

```
Docker version 17.05.0-ce, build 89658be
```

- Output of `docker info`:

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 10
Server Version: 17.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-83-generic
Operating System: Ubuntu 16.04.2 LTS (containerized)
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 58.97GiB
Name: dockerdev
ID: UKK3:F654:IPZA:MY5T:4GQJ:4OCS:4DKN:H2M4:EIDD:B2MW:RLXU:JBLE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: chipironcin
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.14.0, build c7bdf9e
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Amazon EC2, Docker in Docker

**Comment by andresbono** [comment]
Hi @chipironcin, we have just removed the variable from the `README.md`. Thanks.
