### ISSUE TITLE
sendmail don't work in default docker-compose installation 

### ISSUE THREAD

**Issue by mvmendes** [bitnami/bitnami-docker-dreamfactory#9]
When installing a fresh version of  dream-factory docker-compose, the funcionalities that depends of /usr/sbin/sendmail didn't work because this package wasn't installed by default in bitnami/dreamfactory:latest image  

**Steps to reproduce the issue:**

1. Install docker-compose:
$ curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-dreamfactory/master/docker-compose.yml > docker-compose.yml
$ docker-compose up -d

2. Setup admin, configure app demo,...
3. Create a new user and try to send an invite by mail.

**The system's response is "/usr/sbin/sendmail was not found"...**
 
In order to get it work, I have installed the sendmail package into container's console:

```
$ sudo apt-get update
$ sudo apt-get install sendmail
```
And after installed, run this configure tool: 
```
$ /usr/sbin/sendmailconfig
Configure sendmail with the existing /etc/mail/sendmail.conf? [Y]
Reading configuration from /etc/mail/sendmail.conf.
Validating configuration.
Writing configuration to /etc/mail/sendmail.conf.
Writing /etc/cron.d/sendmail.
Configure sendmail with the existing /etc/mail/sendmail.mc? [Y] N << Answer "N" to reconfigure mail parameters
```

**Comment by jotadrilo** [comment]
Hi @mvmendes,

Thanks for spotting this issue. We are evaluating whether to ship and configure `sendmail` in the Dream Factory container.

As a temporary workaround, you could inherit from the latest image and perform two additional steps:

```
RUN install_packages sendmail && \
    yes 'y' | /usr/sbin/sendmailconfig
```

I hope it helps!

- - - - - - - - - - - - -
Was my answer helpful? Click on :heart:

**Comment by mvmendes** [comment]
Hi @jotadrilo,

I had installed the package and I configured sendmail property before this ticket, and yes, it work properly after that.

Thanks!
